# name of the action
name: push

# trigger on push events
on:
  push:

# pipeline to execute
jobs:
  pushing:
    runs-on: ubuntu-latest
    container:
      image: golang:latest
    steps:
      - name: clone
        uses: actions/checkout@v2

      - name: build
        run: |
          GO_VERSION=$(go version)

          go build \
            -ldflags "-X main.Git=${GITHUB_SHA} main.Go=${GO_VERSION}" \
            -o release/test
             
      - name: execute
        run: |
          ./release/test
