# name of the action
name: push

# trigger on push events
on:
  push:

# pipeline to execute
jobs:
  pushing:
    runs-on: ubuntu-latest
    container:
      image: golang:latest
    steps:
      - name: clone
        uses: actions/checkout@v2

      - name: build
        run: |
          go build \
            -ldflags "-X main.App=${GITHUB_TAG} -X main.Git=${GITHUB_SHA} -X main.Lang=${GOLANG_VERSION}" \
            -o release/test

      - name: execute
        run: |
          ./release/test
