# name of the action
name: push

# trigger on push events
on:
  push:

# pipeline to execute
jobs:
  pushing:
    runs-on: ubuntu-latest
    container:
      image: golang:latest
    steps:
      - name: clone
        uses: actions/checkout@v3

      - name: install
        run: |
          go get github.com/ahmetb/govvv

      - name: output
        run: |
          govvv build -o release/test -print -version v0.1.0

      - name: build
        run: |
          govvv build -o release/test -version v0.1.0

      - name: execute
        run: |
          ./release/test
