# name of the action
name: tag

# trigger on push events with tag
on:
  push:
    tags:
      - '*'

# pipeline to execute
jobs:
  tagging:
    runs-on: ubuntu-latest
    container:
      image: golang:latest
    steps:
      - name: clone
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: env
        run: |
          echo ${GITHUB_REF#refs/tags/}
          echo "GITHUB_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

      - name: test
        run: |
          echo ${GITHUB_TAG}

      - name: build
        run: |
          go build \
            -ldflags="-X main.App=${GITHUB_TAG} main.Arch=foo main.Built=$(date) main.Git=${GITHUB_SHA} main.Go=$(go version)" \
            -o release/test

      - name: execute
        run: |
          ./release/test
