# name of the action
name: test

# trigger on push events with tag
on:
  push:
    tags:

# pipeline to execute
jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: golang:latest
    steps:
      - name: clone
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
          
      - name: env
        run: |
          echo ${GITHUB_REF#refs/tags/}
          echo "GITHUB_TAG=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
